// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpHan3inizB2iK55f27ENRJAVzSiHdO8',
    appId: '1:1064612831367:web:6d18cc33ad61d277da5822',
    messagingSenderId: '1064612831367',
    projectId: 'chat-app-51124',
    authDomain: 'chat-app-51124.firebaseapp.com',
    storageBucket: 'chat-app-51124.appspot.com',
    measurementId: 'G-ZNN0R4CQQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS9lqfm0lLRr2otAZjFPKab4Gu34b9G2I',
    appId: '1:1064612831367:android:82ebf35a2984ef42da5822',
    messagingSenderId: '1064612831367',
    projectId: 'chat-app-51124',
    storageBucket: 'chat-app-51124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQI11ACOzd9ncDXnGV-hWutKinzyrM1kA',
    appId: '1:1064612831367:ios:74800e1cc98efe44da5822',
    messagingSenderId: '1064612831367',
    projectId: 'chat-app-51124',
    storageBucket: 'chat-app-51124.appspot.com',
    iosClientId: '1064612831367-9aoncmhfe64oj5uf4ur9pli28ds03mes.apps.googleusercontent.com',
    iosBundleId: 'com.example.ch',
  );
}
